//
// Created by chouryzhou on 24-11-1.
//

#ifndef BPF_CALL_H
#define BPF_CALL_H

#include <stdint.h>

#define BPF_CALL_BASE 0x10000u
#define BPF_CALL_ID(id) (BPF_CALL_BASE + (uint32_t)(id))
#define BPF_CALL_TO_ID(call) ((uint32_t)(call) - BPF_CALL_BASE)

enum bpf_syscall_id {
    BPF_SYS_MMAP = 1,
    BPF_SYS_MUNMAP,
    BPF_SYS_EXIT,
    BPF_SYS_GETTIMEOFDAY,
    BPF_SYS_TIMES,
    BPF_SYS_OPEN,
    BPF_SYS_READ,
    BPF_SYS_WRITE,
    BPF_SYS_LSEEK,
    BPF_SYS_CLOSE,
    BPF_SYS_UNLINK,
    BPF_SYS_RENAMEAT,
    BPF_SYS_READLINK,
    BPF_SYS_EXECVE,
    BPF_SYS_FORK,
    BPF_SYS_GETPID,
    BPF_SYS_GETPPID,
    BPF_SYS_WAITPID,
    BPF_SYS_KILL,
    BPF_SYS_SIGACTION,
    BPF_SYS_DUP2,
    BPF_SYS_PIPE2,
    BPF_SYS_CHDIR,
    BPF_SYS_GETCWD,
    BPF_SYS_DUP,
    BPF_SYS_FCNTL,
    BPF_SYS_IOCTL,

    BPF_SYS_STAT,
    BPF_SYS_LSTAT,
    BPF_SYS_FSTAT,
    BPF_SYS_UMASK,
    BPF_SYS_OPENDIR,
    BPF_SYS_READDIR,
    BPF_SYS_CLOSEDIR,
    BPF_SYS_MKDIR,
    BPF_SYS_RMDIR,
    BPF_SYS_SETJMP,
    BPF_SYS_LONGJMP,
};

#define BPF_CALL_MMAP      BPF_CALL_ID(BPF_SYS_MMAP)
#define BPF_CALL_MUNMAP    BPF_CALL_ID(BPF_SYS_MUNMAP)
#define BPF_CALL_EXIT      BPF_CALL_ID(BPF_SYS_EXIT)
#define BPF_CALL_GETTIMEOFDAY      BPF_CALL_ID(BPF_SYS_GETTIMEOFDAY)
#define BPF_CALL_TIMES     BPF_CALL_ID(BPF_SYS_TIMES)
#define BPF_CALL_OPEN      BPF_CALL_ID(BPF_SYS_OPEN)
#define BPF_CALL_READ      BPF_CALL_ID(BPF_SYS_READ)
#define BPF_CALL_WRITE     BPF_CALL_ID(BPF_SYS_WRITE)
#define BPF_CALL_LSEEK     BPF_CALL_ID(BPF_SYS_LSEEK)
#define BPF_CALL_CLOSE     BPF_CALL_ID(BPF_SYS_CLOSE)
#define BPF_CALL_UNLINK    BPF_CALL_ID(BPF_SYS_UNLINK)
#define BPF_CALL_RENAMEAT  BPF_CALL_ID(BPF_SYS_RENAMEAT)
#define BPF_CALL_READLINK  BPF_CALL_ID(BPF_SYS_READLINK)
#define BPF_CALL_EXECVE    BPF_CALL_ID(BPF_SYS_EXECVE)
#define BPF_CALL_FORK      BPF_CALL_ID(BPF_SYS_FORK)
#define BPF_CALL_KILL      BPF_CALL_ID(BPF_SYS_KILL)
#define BPF_CALL_SIGACTION BPF_CALL_ID(BPF_SYS_SIGACTION)
#define BPF_CALL_GETPID    BPF_CALL_ID(BPF_SYS_GETPID)
#define BPF_CALL_GETPPID   BPF_CALL_ID(BPF_SYS_GETPPID)
#define BPF_CALL_WAITPID   BPF_CALL_ID(BPF_SYS_WAITPID)
#define BPF_CALL_DUP2      BPF_CALL_ID(BPF_SYS_DUP2)
#define BPF_CALL_PIPE2     BPF_CALL_ID(BPF_SYS_PIPE2)
#define BPF_CALL_CHDIR     BPF_CALL_ID(BPF_SYS_CHDIR)
#define BPF_CALL_GETCWD    BPF_CALL_ID(BPF_SYS_GETCWD)
#define BPF_CALL_DUP       BPF_CALL_ID(BPF_SYS_DUP)
#define BPF_CALL_FCNTL     BPF_CALL_ID(BPF_SYS_FCNTL)
#define BPF_CALL_IOCTL     BPF_CALL_ID(BPF_SYS_IOCTL)

#define BPF_CALL_STAT      BPF_CALL_ID(BPF_SYS_STAT)
#define BPF_CALL_LSTAT     BPF_CALL_ID(BPF_SYS_LSTAT)
#define BPF_CALL_FSTAT     BPF_CALL_ID(BPF_SYS_FSTAT)
#define BPF_CALL_UMASK     BPF_CALL_ID(BPF_SYS_UMASK)
#define BPF_CALL_OPENDIR   BPF_CALL_ID(BPF_SYS_OPENDIR)
#define BPF_CALL_READDIR   BPF_CALL_ID(BPF_SYS_READDIR)
#define BPF_CALL_CLOSEDIR  BPF_CALL_ID(BPF_SYS_CLOSEDIR)
#define BPF_CALL_MKDIR     BPF_CALL_ID(BPF_SYS_MKDIR)
#define BPF_CALL_RMDIR     BPF_CALL_ID(BPF_SYS_RMDIR)

#define BPF_CALL_SETJMP    BPF_CALL_ID(BPF_SYS_SETJMP)
#define BPF_CALL_LONGJMP   BPF_CALL_ID(BPF_SYS_LONGJMP)

#endif //BPF_CALL_H
