//
// Created by chouryzhou on 24-11-1.
//

#ifndef BPF_CALL_H
#define BPF_CALL_H

#include <stdint.h>

#define BPF_CALL_BASE 0x10000u
#define BPF_CALL_ID(id) (BPF_CALL_BASE + (uint32_t)(id))
#define BPF_CALL_TO_ID(call) ((uint32_t)(call) - BPF_CALL_BASE)

enum bpf_syscall_id {
    BPF_SYS_MMAP = 1,
    BPF_SYS_MUNMAP,
    BPF_SYS_EXIT,
    BPF_SYS_OPENAT,
    BPF_SYS_READ,
    BPF_SYS_WRITE,
    BPF_SYS_LSEEK,
    BPF_SYS_CLOSE,
    BPF_SYS_UNLINKAT,
    BPF_SYS_RENAMEAT,
    BPF_SYS_READLINK,
    BPF_SYS_EXECVE,
    BPF_SYS_FORK,
    BPF_SYS_GETPID,
    BPF_SYS_GETPPID,
    BPF_SYS_WAITPID,
    BPF_SYS_KILL,
    BPF_SYS_SIGACTION,
    BPF_SYS_DUP2,
    BPF_SYS_PIPE2,
    BPF_SYS_FCHDIR,
    BPF_SYS_GETCWD,
    BPF_SYS_DUP,
    BPF_SYS_FCNTL,
    BPF_SYS_IOCTL,
    BPF_SYS_FSTATAT,
    BPF_SYS_FCHMODAT,
    BPF_SYS_UTIMENSAT,
    BPF_SYS_FACCESSAT,
    BPF_SYS_UMASK,
    BPF_SYS_FDOPENDIR,
    BPF_SYS_READDIR,
    BPF_SYS_CLOSEDIR,
    BPF_SYS_MKDIR,
    BPF_SYS_RMDIR,
    BPF_SYS_SYMLINKAT,
    BPF_SYS_LINKAT,
    BPF_SYS_SETJMP,
    BPF_SYS_LONGJMP,
    BPF_SYS_NANOSLEEP,
    BPF_SYS_CLOCK_GETTIME,
    BPF_SYS_TRUNCATE,
    BPF_SYS_FTRUNCATE,
    BPF_SYS_MPROTECT,       // mprotect(addr, len, prot)
    BPF_SYS_READV,          // readv(fd, iov, iovcnt)
    BPF_SYS_WRITEV,         // writev(fd, iov, iovcnt)
    BPF_SYS_PREAD,          // pread(fd, buf, count, off)
    BPF_SYS_PWRITE,         // pwrite(fd, buf, count, off)
    BPF_SYS_GETRANDOM,      // getrandom(buf, buflen, flags)
    BPF_SYS_GETDENTS64,     // 64 位目录项读取，musl readdir 走此路
    BPF_SYS_SET_TID_ADDRESS,// set_tid_address(tidptr) — 后续 futex/线程退出清零点
    BPF_SYS_EXIT_GROUP,     // 进程退出（无线程时等价于 exit）
    BPF_SYS_MADVISE,        // madvise — 不实现，返回 -ENOSYS
    BPF_SYS_SCHED_YIELD,    // sched_yield() — 让出执行（JIT 安全点）
    BPF_SYS_GETTID,         // gettid()
};

#define BPF_CALL_MMAP      BPF_CALL_ID(BPF_SYS_MMAP)
#define BPF_CALL_MUNMAP    BPF_CALL_ID(BPF_SYS_MUNMAP)
#define BPF_CALL_EXIT      BPF_CALL_ID(BPF_SYS_EXIT)
#define BPF_CALL_OPENAT    BPF_CALL_ID(BPF_SYS_OPENAT)
#define BPF_CALL_READ      BPF_CALL_ID(BPF_SYS_READ)
#define BPF_CALL_WRITE     BPF_CALL_ID(BPF_SYS_WRITE)
#define BPF_CALL_LSEEK     BPF_CALL_ID(BPF_SYS_LSEEK)
#define BPF_CALL_CLOSE     BPF_CALL_ID(BPF_SYS_CLOSE)
#define BPF_CALL_UNLINKAT  BPF_CALL_ID(BPF_SYS_UNLINKAT)
#define BPF_CALL_RENAMEAT  BPF_CALL_ID(BPF_SYS_RENAMEAT)
#define BPF_CALL_READLINK  BPF_CALL_ID(BPF_SYS_READLINK)
#define BPF_CALL_EXECVE    BPF_CALL_ID(BPF_SYS_EXECVE)
#define BPF_CALL_FORK      BPF_CALL_ID(BPF_SYS_FORK)
#define BPF_CALL_KILL      BPF_CALL_ID(BPF_SYS_KILL)
#define BPF_CALL_SIGACTION BPF_CALL_ID(BPF_SYS_SIGACTION)
#define BPF_CALL_GETPID    BPF_CALL_ID(BPF_SYS_GETPID)
#define BPF_CALL_GETPPID   BPF_CALL_ID(BPF_SYS_GETPPID)
#define BPF_CALL_WAITPID   BPF_CALL_ID(BPF_SYS_WAITPID)
#define BPF_CALL_DUP2      BPF_CALL_ID(BPF_SYS_DUP2)
#define BPF_CALL_PIPE2     BPF_CALL_ID(BPF_SYS_PIPE2)
#define BPF_CALL_FCHDIR    BPF_CALL_ID(BPF_SYS_FCHDIR)
#define BPF_CALL_GETCWD    BPF_CALL_ID(BPF_SYS_GETCWD)
#define BPF_CALL_DUP       BPF_CALL_ID(BPF_SYS_DUP)
#define BPF_CALL_FCNTL     BPF_CALL_ID(BPF_SYS_FCNTL)
#define BPF_CALL_IOCTL     BPF_CALL_ID(BPF_SYS_IOCTL)
#define BPF_CALL_FSTATAT   BPF_CALL_ID(BPF_SYS_FSTATAT)
#define BPF_CALL_FCHMODAT  BPF_CALL_ID(BPF_SYS_FCHMODAT)
#define BPF_CALL_UTIMENSAT BPF_CALL_ID(BPF_SYS_UTIMENSAT)
#define BPF_CALL_FACCESSAT BPF_CALL_ID(BPF_SYS_FACCESSAT)
#define BPF_CALL_UMASK     BPF_CALL_ID(BPF_SYS_UMASK)
#define BPF_CALL_FDOPENDIR BPF_CALL_ID(BPF_SYS_FDOPENDIR)
#define BPF_CALL_READDIR   BPF_CALL_ID(BPF_SYS_READDIR)
#define BPF_CALL_CLOSEDIR  BPF_CALL_ID(BPF_SYS_CLOSEDIR)
#define BPF_CALL_MKDIR     BPF_CALL_ID(BPF_SYS_MKDIR)
#define BPF_CALL_RMDIR     BPF_CALL_ID(BPF_SYS_RMDIR)
#define BPF_CALL_SYMLINKAT BPF_CALL_ID(BPF_SYS_SYMLINKAT)
#define BPF_CALL_LINKAT    BPF_CALL_ID(BPF_SYS_LINKAT)
#define BPF_CALL_SETJMP    BPF_CALL_ID(BPF_SYS_SETJMP)
#define BPF_CALL_LONGJMP   BPF_CALL_ID(BPF_SYS_LONGJMP)
#define BPF_CALL_NANOSLEEP BPF_CALL_ID(BPF_SYS_NANOSLEEP)
#define BPF_CALL_CLOCK_GETTIME BPF_CALL_ID(BPF_SYS_CLOCK_GETTIME)
#define BPF_CALL_TRUNCATE  BPF_CALL_ID(BPF_SYS_TRUNCATE)
#define BPF_CALL_FTRUNCATE BPF_CALL_ID(BPF_SYS_FTRUNCATE)
#define BPF_CALL_MPROTECT  BPF_CALL_ID(BPF_SYS_MPROTECT)
#define BPF_CALL_READV     BPF_CALL_ID(BPF_SYS_READV)
#define BPF_CALL_WRITEV    BPF_CALL_ID(BPF_SYS_WRITEV)
#define BPF_CALL_PREAD     BPF_CALL_ID(BPF_SYS_PREAD)
#define BPF_CALL_PWRITE    BPF_CALL_ID(BPF_SYS_PWRITE)
#define BPF_CALL_GETRANDOM BPF_CALL_ID(BPF_SYS_GETRANDOM)
#define BPF_CALL_GETDENTS64 BPF_CALL_ID(BPF_SYS_GETDENTS64)
#define BPF_CALL_SET_TID_ADDRESS BPF_CALL_ID(BPF_SYS_SET_TID_ADDRESS)
#define BPF_CALL_EXIT_GROUP BPF_CALL_ID(BPF_SYS_EXIT_GROUP)
#define BPF_CALL_MADVISE   BPF_CALL_ID(BPF_SYS_MADVISE)
#define BPF_CALL_SCHED_YIELD BPF_CALL_ID(BPF_SYS_SCHED_YIELD)
#define BPF_CALL_GETTID    BPF_CALL_ID(BPF_SYS_GETTID)

#endif //BPF_CALL_H
